[workspace]
members = [
    "geocoder",
    "web"
]

[workspace.package]
version = "0.2.0"
authors = ["Christoph von Kr√ºchten <cvk@treestack.de>"]
description = "Reverse geocoder microservice"
documentation = "https://github.com/treestack/geocoder"
